sudo: required
services:
  - docker

before_install:
  - docker build -t desyatkov/docker-react:0.1 -f Dockerfile.dev .

script:
  - docker run desyatkov/docker-react:0.1 npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-300760820671"
#   backet_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"